### ISSUE TITLE
写成shell，依赖不会多

### ISSUE THREAD

**Issue by mchome** [mynuolr/GDCTSCP#5]
自带的busybox的ash, md5sum, curl就可以了 :)

**Comment by mynuolr** [comment]
应该可以~登陆的第二次post需要第一次post返回的一个验证码。

**Comment by mchome** [comment]
awk or grep 可以过滤出来 :+1:

**Comment by mynuolr** [comment]
那就可以了。我想写c的，可惜不会，你会吗？

**Comment by mchome** [comment]
shell大法好 :)

**Comment by mchome** [comment]
给你份以前写的好像不能用但是修改下应该可以用的? http://pastebin.com/s3F5pdE5  :)

**Comment by mynuolr** [comment]
你抓一下包，看一下数据吧，注意一下

**Comment by mchome** [comment]
不，是给你的，我不用这玩意，之前给学弟测试说不行

**Comment by mynuolr** [comment]
我不用SHELL，py大法好
